[package]
name = "lluvia_media"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


# Try to keep the dependencies to a minimum
[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
bytes = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
wasm-bindgen-test = { workspace = true }


[lib]
name = "lluvia_media"
crate-type = ["cdylib", "rlib"]


# [lints.rust]
# unexpected_cfgs = { level = "deny", check-cfg = ['cfg(python_bindings)'] }
