[package]
name = "lluvia_media"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


# Try to keep the dependencies to a minimum
[dependencies]
thiserror = { version = "1.0.63" }
anyhow = { version = "*" }
clap = { version = "4.5.4", features = ["derive"] }
bytes = { version = "1.9.0" }

[dev-dependencies]
rstest = { version = "0.18.2" }


[lib]
name = "lluvia_media"
crate-type = ["cdylib"]


# [lints.rust]
# unexpected_cfgs = { level = "deny", check-cfg = ['cfg(python_bindings)'] }
