[package]
name = "lluvia_vk"
version = "0.1.0"
edition = "2024"

[dependencies]
bon = { workspace = true }
bytemuck = { workspace = true }
foldhash = { workspace = true }
include_dir = { workspace = true }
mlua = { workspace = true }
thiserror = { workspace = true }
vulkano = { workspace = true }


[dev-dependencies]
anyhow = { workspace = true }
vulkano-shaders = { workspace = true }
